[tool.poetry]
name = "webcap"
version = "0.1.0"
description = "An ultra-lightweight web screenshot tool written in Python"
authors = ["TheTechromancer"]
repository = "https://github.com/blacklanternsecurity/webcap"
homepage = "https://github.com/blacklanternsecurity/webcap"
license = "GPL-v3.0"
readme = "README.md"
keywords = ["python", "cli", "web", "screenshot", "osint", "ocr", "bug-bounty", "bugbounty", "headless", "web-browser", "scanner", "python-library", "hacking", "pentesting", "recon"]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Topic :: Security",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
httpx = "^0.28.0"
websockets = ">=14.1,<16.0"
orjson = "^3.10.12"
uvloop = "^0.21.0"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
rich = ">=13.9.4,<15.0.0"
extractous = "^0.3.0"
pillow = "^11.1.0"
numpy = ">=2.0.2,<2.1.0"
typer = "^0.15.2"

[tool.poetry.scripts]
webcap = "webcap.cli:main"

[tool.ruff]
line-length = 119
lint.ignore = ["E402", "E721", "E741", "F401", "F403", "F405", "E713"]

[tool.poetry.group.dev.dependencies]
ruff = "==0.11.10"
pytest-httpserver = "^1.1.0"
pytest-asyncio = "^0.25.2"
poetry-dynamic-versioning = "^1.4.1"
pytest-cov = "^6.0.0"
lxml = "^5.3.0"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
metadata = true
