name: Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  python:
    uses: blacklanternsecurity/CLA/.github/workflows/python-tests.yml@40c6e18c0a6e32116eea4f89fc826f53c70889dc # 2026-10-07
    with:
      setup-script: scripts/ci-setup.sh
      pytest-args: -s -vv --disable-warnings --cov-report xml:cov.xml --cov=webcap .
      coverage: true
    secrets: inherit
